#    ________  ________  _______   ________   ________  ________  ________  ___  __    ________
#   |\   __  \|\   __  \|\  ___ \ |\   ___  \|\   __  \|\   __  \|\   __  \|\  \|\  \ |\   ____\
#   \ \  \|\  \ \  \|\  \ \   __/|\ \  \\ \  \ \  \|\ /\ \  \|\  \ \  \|\  \ \  \/  /|\ \  \___|_
#    \ \  \\\  \ \   ____\ \  \_|/_\ \  \\ \  \ \   __  \ \  \\\  \ \  \\\  \ \   ___  \ \_____  \
#     \ \  \\\  \ \  \___|\ \  \_|\ \ \  \\ \  \ \  \|\  \ \  \\\  \ \  \\\  \ \  \\ \  \|____|\  \
#      \ \_______\ \__\    \ \_______\ \__\\ \__\ \_______\ \_______\ \_______\ \__\\ \__\____\_\  \
#       \|_______|\|__|     \|_______|\|__| \|__|\|_______|\|_______|\|_______|\|__| \|__|\_________\
#                                                                                        \|_________|
# Open Books when user joins

# Books that OpenBooks should read when the plugin starts
BooksToLoad: ["JoinBook", "NewUserBook"]
# Book name that OpenBooks should show player when they join the server
UserJoinBook: "JoinBook"
# UserJoinBook: ""  # If you do not want to open a book when user joins
# Book name that OpenBooks should show player when they join the server for the first time.
NewUserJoinBook: "NewUserBook"
# NewUserJoinBook: "" # If you do not want to open a book when user joins the server for the first time.
# We have en, ko locale. If you can translate, please provide translation